### ISSUE TITLE
Problem with MessageStore Option

### ISSUE THREAD

**Issue by bwatkins79** [cosullivan/SmtpServer#11]
Hello, I love this project.  I was using an older version of this (1.2.2.0) with no issues. I'm working on updating my project and with v1.6 I can't get the MessageStore option to work. It is saying that it only takes IMessageStoreFactory as its argument. I tried changing my ConsoleMessageStore to an IMessageStoreFactory, but it told me 'WindowsService1.ConsoleMessageStore' does not implement interface member 'SmtpServer.Storage.IMessageStoreFactory.CreateInstance(SmtpServer.ISessionContext)'   

Any suggestions on how to work around this?

**Comment by cosullivan** [comment]
Hi, glad to hear that you like the project.

I modified the server to allow for per-session instances of the IMessageStore based on the current session context (ie, the remote client IP address). This is why it now uses an IMessageStoreFactory as opposed to simply taking an IMessageStore instance.

If you want the previous behavior, I've added an abstract SmtpServer.Storage.MessageStore class which you can inherit from instead. Have a look at that class as it is pretty basic.

Thanks,
Cain
